import React,{useState, useEffect} from 'react';
import {Link} from 'react-router-dom';
import { useNavigate } from 'react-router'
//import 'bootstrap/dist/css/bootstrap.min.css';
//import '../../css/Scaffold.css';

import imgfile from '../../img/save.png';
import imgfile2 from '../../img/results.png';
import imgfile3 from '../../img/results2.png';
import imgfile4 from '../../img/results3.png';
import imgfile5 from '../../img/results4.png';
import imgfile6 from '../../img/results6.png';
import imgfile7 from '../../img/results7.png';
import imgfile8 from '../../img/drawio1.png';
import imgfile9 from '../../img/drawio2.png';
import { Container,Col,Row,Image,Modal,Button,ButtonToolbar} from 'react-bootstrap';

function Scaffold(props){
    const [show, setShow] = useState(false);

    const goEmpty = (e) => {


      localStorage.removeItem('interitem3')
      localStorage.removeItem('reset2')
      localStorage.removeItem('decision')
      localStorage.removeItem('getitem2')
      localStorage.removeItem('reset1')
      localStorage.removeItem('getitem1')
      localStorage.removeItem('resultID')
      localStorage.removeItem('SID')
      localStorage.removeItem('AID')
      localStorage.removeItem('EXPID')
      localStorage.removeItem('ProjectID2')
      localStorage.removeItem('ProjectID')
      };
      
      
      
    /* <Image
      src={imgfile}
      className='img-thumbnail'
      alt='...'
      style={{ maxWidth: '24rem' }}/> */
      
      //    style={{"height":'none',backgroundImage: `url(${imgfile}` }} imgfile2imgfile3imgfile4imgfile5
 //localStorage.clear()
    return(<>
{

goEmpty()

//interitem3,reset2,decision,getitem2,reset1,getitem1,resultID,SID,AID,EXPID,ProjectID2,ProjectID






}
   
    <Container id ='wholeT'>
    <Row style={{"padding":'1%'}}  >
      <br/>
    </Row>
    <Row style={{"padding":'1%'}}  >
    <Col  lg={6} sm={12} md={10}  >
    <text style={{ "font-size": "15px",'fontWeight': 'bold',textAlign: "left","display": "flex"}}>
    Platform workflow
   
    </text>

    <Image 
      src={imgfile9}
      className='img-thumbnail'
      alt='...'
      />
     </Col>
     <Col lg={6} sm={12} md={10} >
     <text style={{ "font-size": "15px",'fontWeight': 'bold',textAlign: "left","display": "flex"}}>
     Visualization Chart and icon
    

     </text>

     <Image
      src={imgfile8}
      className='img-thumbnail'
      alt='...'
      />
     </Col>
     

      </Row>

  <Row style={{"margin":'1%'}} >
     
     
      <Col  lg ={{ span: 12 }} sm ={{ span:12 }}   className="justify-content-md-center">
      
     
      <text style={{ "font-size": "15px",'fontWeight': 'bold',textAlign: "center","display": "flex"}}  >  Abstract </text>
      <br/>
      <text style={{ "font-size": "12px",textAlign: "left"}}  >  

      With advances in NGS, genomics continued to be studied and advanced. Since then, it has become important to study proteins that perform multiple functions in cells.  For this reason, proteomics research to confirm and analyze protein expression has been actively conducted in recent years. With the development of MS(Mass spectrometry)-based PROTEOMICS, it became possible to identify proteins from mixed and complex samples. This enabled researchers to analyze the produced proteomics data and conduct various additional studies such as protein identification, protein profiling, interaction analysis, ptm identification, and protein quantification. In Proteomics, the research results of researchers were classified by recording metadata such as research purpose, experimental method, species, analytical instrument, tag, and treat. And to manage the raw data of the experiment, the data generated by MS was uploaded to PRIDE so that it can be used as public proteomics data. 
 We upload proteingroups file, which is the result of quantifying proteome raw data through maxquant, and make it a DB, and select the uploaded file to find proteins affected by processing through DEP analysis. We visualize the researcher's analysis results based on the DEP results and show them through the page. For visualization, we use react library react google chart, react force graph, react-d3. 
 Upload a quantified file of RAW data through this platform, select the uploaded data and analyze it. So you get a list of significant proteins. and We expect to be able to understand the relationship between proteins (experiment) and proteins(known) through network analysis.
In addition, we expect that we will be able to view research from a different angle and gain insight by sharing the research results by converting the uploaded data to public.

          </text>
    
      </Col>
  </Row>
  <Row   >
<Col style={{"margin":'1%' ,"display": "flex","justify-content": "center"}} >
 <a role="button" id="STARTbt"  variant="link"   style={{ "font-size": "35px"}}   href="/Onestep">Get started!</a>
 </Col>
 </Row>
 <br/>
 <br/>

</Container>

    </>
      )

}
export default Scaffold;